import os
from pathlib import Path
import re

BOT_DIR = Path("Bot")
BOTS_DIR = BOT_DIR / "Bots"
OUTPUT_FILE = Path("BotMerged.cs")

FILES_ORDER = [
    "BotSetup.cs",
    "Utils.cs",
    "Move.cs",
    "GameStateBit.cs",
    "GameStateReader.cs",
    "Phases/OpeningPhase.cs",
    "Phases/DevelopmentPhase.cs",
    "Phases/CombatPhase.cs",
    "Bots/AI.cs",
    "Bots/CoverBot.cs",
    "Bots/Mikasa.cs",
    "Program.cs"
]

all_usings = set()
merged_code = []

def extract_codingame_main(lines):
    """Wyciąga tylko #if CODINGAME blok z Program.cs"""
    inside = False
    block = []
    for line in lines:
        if "#if CODINGAME" in line:
            inside = True
            continue
        if "#else" in line:
            inside = False
            continue
        if "#endif" in line:
            break
        if inside:
            block.append(line)
    return block

def clean_and_collect(file_path, is_program=False):
    with open(file_path, encoding="utf-8") as f:
        lines = f.readlines()

    if is_program:
        lines = extract_codingame_main(lines)

    code = []
    for line in lines:
        stripped = line.strip()

        # Collect using
        if stripped.startswith("using "):
            all_usings.add(stripped)
            continue

        # Remove namespace lines
        if stripped.startswith("namespace "):
            continue

        # Remove preprocessor directives
        if stripped.startswith("#"):
            continue

        code.append(line)

    return code

for file in FILES_ORDER:
    path = (BOT_DIR / file) if (BOT_DIR / file).exists() else (BOTS_DIR / file)
    if not path.exists():
        print(f"[WARN] Missing file: {file}")
        continue

    is_program = (file == "Program.cs")
    code = clean_and_collect(path, is_program=is_program)

    merged_code.append(f"// ===== {file} =====\n")
    merged_code.extend(code)
    merged_code.append("\n\n")

# Then write to file
with open(OUTPUT_FILE, "w", encoding="utf-8") as out:
    out.write("// Merged bot for Codingame – generated by merge_bot.py\n")
    out.write("// Paste into Codingame editor\n\n")

    # Write collected usings at the top
    for u in sorted(all_usings):
        out.write(u + "\n")
    out.write("\n")

    out.writelines(merged_code)

print(f"[OK] Bot merged to: {OUTPUT_FILE}")
